[package]
name = "casperfpga_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
kstring = "2"

[dependencies.casper_utils]
path = "../casper_utils"
version = "0.1.0"

[lib]
proc_macro = true
