on: push
name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Lint (clippy)
        run: cargo clippy --all-targets -- -D warnings
      - name: Lint (rustfmt)
        run: cargo fmt --all -- --check

  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable, "1.71", nightly]
        target: [x86_64-unknown-linux, aarch64-unknown-linux-gnu]
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache Rust deps
        uses: Swatinem/rust-cache@v2
      
      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          args: "--all-targets"
          strip: true
          toolchain: ${{ matrix.rust-version }}
          target: ${{ matrix.target }}

      - name: Test
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          args: "--all-targets"
          strip: true
          toolchain: ${{ matrix.rust-version }}
          target: ${{ matrix.target }}

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        if: startsWith(matrix.rust-version, 'stable') && startsWith(matrix.target, 'x86_64-unknown-linux')
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        if: startsWith(matrix.rust-version, 'stable') && startsWith(matrix.target, 'x86_64-unknown-linux')
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
